### PR TITLE
fix: correctly calculate `path` when `pathMatch` is empty string (fix #3106)

### LINKED ISSUE #3106: push to named star route with empty pathMatch fails
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/vue-template-7k3sv](https://codesandbox.io/s/vue-template-7k3sv)

### Steps to reproduce
1. Open https://codesandbox.io/s/vue-template-7k3sv
1. Click [button 1]. Note you get to `https://7k3sv.csb.app/anything/123` - which is ok.
1. Click [button 2].

### What is expected?
You should get to `https://7k3sv.csb.app/anything/`.

### What is actually happening?
You get to `https://7k3sv.csb.app/`.

---
I checked a couple of vue-router issues in the past, and I noticed posva has his own particular way of assessing bugs, so I know he will say this is not a bug. But is there anyone in vue-router team willing to acknowledge this is a bug? (cc @yyx990803, @kazupon)

I used the latest vue-router available on npm (3.1.5). My current issue report says I used 3.1.3 because new-issue.vuejs.org does not let me choose 3.1.5. Guys, if you force me using new-issue.vuejs.org when reporting an issue, it would be nice to keep it up-to-date.

### PR DESCRIPTION
**Pull request by adi-zz**

### CODE REVIEW

File: src/util/params.js [hunk 1]
```diff
@@ -20,7 +20,8 @@ export function fillParams (
       (regexpCompileCache[path] = Regexp.compile(path))
 
     // Fix #2505 resolving asterisk routes { name: 'not-found', params: { pathMatch: '/not-found' }}
-    if (params.pathMatch) params[0] = params.pathMatch
+    // `params.pathMatch === ''` fixes #3106 so that you can work with location descriptor object having params.pathMatch equal to empty string
+    if (params.pathMatch || params.pathMatch === '') params[0] = params.pathMatch
```
Comment (posva) [inline src/util/params.js]: let's just check if it's a string with a typeof operator

File: test/unit/specs/create-matcher.spec.js [hunk 2]
```diff
@@ -84,4 +84,14 @@ describe('Creating Matcher', function () {
     const { params } = match({ path: '/not-found' }, routes[0])
     expect(params).toEqual({ pathMatch: '/not-found' })
   })
+
+  it('calculates correctly and without warning the path of a partial asterisk route with a default param name and pathMatch empty string', function () {
```
Comment (posva) [inline test/unit/specs/create-matcher.spec.js]:
```suggestion
  it('allows an empty pathMatch', function () {
```

File: test/unit/specs/create-matcher.spec.js [hunk 3]
```diff
@@ -84,4 +84,14 @@ describe('Creating Matcher', function () {
...
+    process.env.NODE_ENV = 'development'
+    const { path } = match(
+      { name: 'error', params: { pathMatch: '' }},
+      routes[0]
+    )
+    expect(console.warn).not.toHaveBeenCalled()
+    expect(path).toEqual('/error/')
```
Comment (posva) [inline test/unit/specs/create-matcher.spec.js]: let's add another assertion with the not found route

**Review by posva — CHANGES_REQUESTED** [review]

**Review by posva — APPROVED** [review]
Thanks!
