### PR TITLE
make a copy when query param value is an array (fix #1182)

### LINKED ISSUE #1182: $router.push({query: this.myarray}) not updating the URL
### Vue.js / vue-router versions
2.1.2

### Reproduction Link
http://jsfiddle.net/ub9e33fm/2/

### Steps to reproduce
1. Click first link
2. Click second link: see the difference in printed vars

### What is Expected?
Clicking the second link will also update `this.$route.query`

### What is actually happening?
`this.$route.query` is not updated

### PR DESCRIPTION
**Pull request by javoski**
fix #1182 
Don't using the object reference as query value directly.

### CODE REVIEW

File: src/util/query.js [hunk 1]
```diff
@@ -19,21 +19,18 @@ export function resolveQuery (
...
-    } catch (e) {
-      process.env.NODE_ENV !== 'production' && warn(false, e.message)
-      parsedQuery = {}
-    }
-    for (const key in extraQuery) {
-      parsedQuery[key] = extraQuery[key]
-    }
-    return parsedQuery
-  } else {
-    return extraQuery
```
Comment (posva) [inline src/util/query.js:35]: It worries me that deleting this part didn't break the test. @fnlctrl Do you have an idea about this?

Comment (javoski) [reply src/util/query.js:35]: There is already an empty value check in parseQuery function.

Comment (posva) [reply src/util/query.js:35]: Yeah, but in the other case we were skipping the whole parseQuery and for loop and returning right away the `extraQuery` instead
