### PR TITLE
Warn about root paths without a leading slash (fix #2550)

### LINKED ISSUE #2550: warn about root paths without a leading slash
### Version
2.5.3

### Reproduction link
[https://codesandbox.io/s/6zvmx5lorr](https://codesandbox.io/s/6zvmx5lorr)

### Example
```js
import Vue from "vue";
import Router from "vue-router";

import Home from "../src/views/Home.vue";
import Products from "../src/views/Products.vue";

Vue.use(Router);

const routes = [
  { name: "home", path: "/", component: Home },
  {
    name: "products",
    path: "products", // <-- the problem is here
    component: Products
  }
];

export default new Router({
  routes
});
```

### Steps to reproduce
1. Open the reproduction
1. Click on the products link

### What is expected?
I spent some time trying to understand what the problem was, so it would be nice to see a warning message telling that the route is invalid because doesn't have the initial slash.

### What is actually happening?
The router goes to a route that doesn't exist.

### PR DESCRIPTION
**Pull request by Sayegh7**
close #2550

This PR creates the following warning message when a root route exists without a leading slash:
screen shot 2019-01-22 at 3 12 15 am

This facilitates the debugging process as the current behavior does not generate any warnings or errors.

### CODE REVIEW

**Review by posva — CHANGES_REQUESTED** [review]
Thanks! We, however, require a test case for this (showing warning vs not showing). The warning should only appear in development mode and it should display more information like the path that may be incorrect. You can check other warnings for inspiration

**Comment by Sayegh7** [comment]
@posva Added test cases, moved the change to `create-route-map`, and included the problematic routes in the warning message

File: src/create-route-map.js [hunk 1]
```diff
@@ -34,6 +34,16 @@ export function createRouteMap (
     }
   }
 
+  // warn if routes do not include leading slashes
+  const pathsMissingSlashes = pathList
```
Comment (posva) [inline src/create-route-map.js]: can you wrap this whole thing so it only gets executed in development?

File: src/create-route-map.js [hunk 2]
```diff
@@ -34,6 +34,16 @@ export function createRouteMap (
...
+    .filter(path => !!path && path.charAt(0) !== '*' && path.charAt(0) !== '/')
```
Comment (posva) [inline src/create-route-map.js]: I think a single `find` is simpler. No need for the map and I don't really understand the last `filter` call
We can also remove the `!!path` check as it's a string

File: src/create-route-map.js [hunk 3]
```diff
@@ -34,6 +34,16 @@ export function createRouteMap (
...
+    .map(path => path.split('/')[0])
+    .filter((path, index, pathList) => pathList.indexOf(path) === index)
+
+  if (pathsMissingSlashes.length > 0) {
+    warn(false, `The following routes require a leading slash in their paths: ${pathsMissingSlashes.join(', ')}`)
```
Comment (posva) [inline src/create-route-map.js]: Printing the one route we found is enough.

```suggestion
    warn(false, `Non-nested routes must include a leading slash character. Replace "${found)" with "/${found}".`)
```

File: test/unit/specs/create-map.spec.js [hunk 4]
```diff
@@ -97,6 +97,48 @@ describe('Creating Route Map', function () {
     expect(console.warn.calls.argsFor(0)[0]).toMatch('vue-router] Duplicate param keys in route with path: "/foo/:id/bar/:id"')
   })
 
+  it('in development, warn if a path is missing a leading slash', function () {
+    process.env.NODE_ENV = 'development'
+    maps = createRouteMap([
+      { path: '/', name: 'home', component: Home },
+      { path: 'bar', name: 'bar', component: Bar },
```
Comment (posva) [inline test/unit/specs/create-map.spec.js]: for this test, bar is enough. We don't even need '/'

File: test/unit/specs/create-map.spec.js [hunk 5]
```diff
@@ -97,6 +97,48 @@ describe('Creating Route Map', function () {
...
+          { path: 'bar/:id', component: Bar }
+        ]
+      },
+      { path: '*', name: 'any', component: Baz }
+    ])
+    expect(console.warn).toHaveBeenCalledTimes(1)
+    expect(console.warn.calls.argsFor(0)[0]).toEqual('[vue-router] The following routes require a leading slash in their paths: bar, foo')
+  })
+
+  it('in development, it has not logged a missing leading slash warning when all paths have slashes', function () {
```
Comment (posva) [inline test/unit/specs/create-map.spec.js]:
```suggestion
  it('in development, it does not log the missing leading slash when routes are valid', function () {
```

File: test/unit/specs/create-map.spec.js [hunk 6]
```diff
@@ -97,6 +97,48 @@ describe('Creating Route Map', function () {
...
+        children: [
+          { path: 'bar/:id', component: Bar }
+        ]
+      },
+      { path: '*', name: 'any', component: Baz }
+    ])
+    expect(console.warn).not.toHaveBeenCalled()
+  })
+
+  it('in production, it has not logged a missing leading slash warning', function () {
```
Comment (posva) [inline test/unit/specs/create-map.spec.js]:
```suggestion
  it('in production, it does not log the missing leading slash warning', function () {
```

File: test/unit/specs/create-map.spec.js [hunk 7]
```diff
@@ -97,6 +97,48 @@ describe('Creating Route Map', function () {
...
+    process.env.NODE_ENV = 'production'
+    maps = createRouteMap([
+      { path: '/', name: 'home', component: Home },
+      { path: 'bar', name: 'bar', component: Bar },
```
Comment (posva) [inline test/unit/specs/create-map.spec.js]: only bar is enough here (1 route)

**Review by posva — CHANGES_REQUESTED** [review]

File: src/create-route-map.js (hunk 2 above)
Comment (Sayegh7) [reply src/create-route-map.js]: `find` is much simpler but unfortunately I do not think it's supported by this version of nightwatch which causes e2e tests to fail.

Comment (posva) [reply src/create-route-map.js]: you are totally right! Thank you for catching that, it would fail on IE as well. Then let's keep the `filter` and display the list of failing routes since the information is there already. If the routes could be displayed one per line, that would be perfect as it would be more readable (I don't remember how it was before)

Comment (Sayegh7) [reply src/create-route-map.js]: It used to be just comma separated, but one per line sounds better

File: src/create-route-map.js [hunk 8]
```diff
@@ -34,6 +34,21 @@ export function createRouteMap (
...
+    const found = pathList
+    // check for missing leading slash
+      .filter(path => path && path.charAt(0) !== '*' && path.charAt(0) !== '/')
+    // split the path to get the root path part only
+      .map(path => path.split('/')[0])
+    // remove duplicates caused by split child paths
+      .filter((path, index, pathList) => pathList.indexOf(path) === index)
+
+    if (found.length > 0) {
+      warn(false, `Non-nested routes must include a leading slash character. Fix the following routes: ${found.join('\n')}.`)
```
Comment (posva) [inline src/create-route-map.js]: the list should be more like

```
[...] routes:
- bar
- foo
```

File: test/unit/specs/create-map.spec.js [hunk 9]
```diff
@@ -97,6 +97,34 @@ describe('Creating Route Map', function () {
...
+      { path: '/bar', name: 'bar', component: Bar }
+    ])
+    expect(console.warn).not.toHaveBeenCalled()
+  })
+
+  it('in production, it does not log the missing leading slash warning', function () {
+    process.env.NODE_ENV = 'production'
+    maps = createRouteMap([
+      { path: '/', name: 'home', component: Home },
+      { path: 'bar', name: 'bar', component: Bar },
```
Comment (posva) [inline test/unit/specs/create-map.spec.js]: only `bar` is enough in this test

File: src/create-route-map.js [hunk 10]
```diff
@@ -34,6 +34,21 @@ export function createRouteMap (
...
 
+  if (process.env.NODE_ENV === 'development') {
+    // warn if routes do not include leading slashes
+    const found = pathList
+    // check for missing leading slash
+      .filter(path => path && path.charAt(0) !== '*' && path.charAt(0) !== '/')
+    // split the path to get the root path part only
+      .map(path => path.split('/')[0])
+    // remove duplicates caused by split child paths
+      .filter((path, index, pathList) => pathList.indexOf(path) === index)
```
Comment (posva) [inline src/create-route-map.js]: I don't think this method is good as it will remove remaining path from `/some/longer/url` when it doesn't have children. So I think there should be some kind of mixing with the `pathMap` to make it display the same path that is displayed with the record, otherwise displaying the whole path seems simpler and easier to spot, even if it could lead to multiple paths when only one record is affected

**Review by posva — CHANGES_REQUESTED** [review]
We are also missing the warning for `addRoutes`. Could you add it as well?

**Comment by Sayegh7** [comment]
@posva Are you referring to the `addRoutes` function used by the matcher? If so, I believe that this function already calls `createRouteMap` which would trigger the warning message.

**Review by posva — APPROVED** [review]
True! I forgot it does an in place thing with the same function

Thanks!
