### PR TITLE
fix(scroll): run scrollBehavior on initial load (fix #3196)

### LINKED ISSUE #3196: scrollBehavior does not run on load
### Version
3.1.6

### Reproduction link
[https://codesandbox.io/s/vue-routing-example-pk4q2](https://codesandbox.io/s/vue-routing-example-pk4q2)

### Steps to reproduce
Load page

### What is expected?
scrollBehavior always return `{ x: 0, y: 200 }` so the scroll position should always be 200 pixels from the top

### What is actually happening?
scrollBehavior always return `{ x: 0, y: 200 }` but scroll position y is always 0 when first loaded

### PR DESCRIPTION
**Pull request by Calvin-LL**
fix #3196 by adding handleScroll to the callback of the first call to history.transitionTo

### CODE REVIEW

**Comment by posva** [comment]
I will first go through https://github.com/vuejs/vue-router/pull/3172 which might create merge conflicts. This will also require an e2e test

**Comment by Calvin-LL** [comment]
> I will first go through #3172 which might create merge conflicts. This will also require an e2e test

Sounds good I'll go add the e2e tests

**Comment by Calvin-LL** [comment]
> I will first go through #3172 which might create merge conflicts. This will also require an e2e test

e2e tests added

**Comment by Calvin-LL** [comment]
> I will first go through #3172 which might create merge conflicts. This will also require an e2e test

Merge conflicts are resolved. Looks like Netlify fail to deploy because of 8d26c5d, not related to this PR

**Comment by Mike377** [comment]
Is this going to be merged soon? Having the same problem right now.

File: test/e2e/specs/scroll-behavior.js [hunk 1]
```diff
@@ -119,6 +119,44 @@ module.exports = {
...
+          return document.getElementById('anchor').getBoundingClientRect().top < 1
+        },
+        null,
+        'scroll to anchor on load'
+      )
+      .url('http://localhost:8080/scroll-behavior/bar#anchor2')
+      .execute(function () {
+        location.reload(true)
+      })
+      .waitForElementVisible('#app', 1000)
```
Comment (posva) [inline test/e2e/specs/scroll-behavior.js]: do we really need the other tests? At the end they are calling the same scrollHandler

File: src/index.js [hunk 2]
```diff
@@ -117,8 +118,17 @@ export default class VueRouter {
     const history = this.history
 
     if (history instanceof HTML5History || history instanceof HashHistory) {
-      const setupListeners = () => {
+      const handleInitialScroll = (route) => {
+        const expectScroll = this.options.scrollBehavior
+        const supportsScroll = supportsPushState && expectScroll
+
+        if (supportsScroll) {
+          handleScroll(this, route, route, false)
```
Comment (posva) [inline src/index.js]: I think it would make sense to pass the initial location as well so get the initial location outside of `handleInitialScroll`

```js
const from = history.current
```

and then do

```js
handleScroll(this, route, from, false)
```

**Review by posva — CHANGES_REQUESTED** [review]

File: test/e2e/specs/scroll-behavior.js (hunk 1 above)
Comment (Calvin-LL) [reply test/e2e/specs/scroll-behavior.js]: make sense, removed redundant tests

File: src/index.js (hunk 2 above)
Comment (Calvin-LL) [reply src/index.js]: make sense, changed in new commit

**Review by posva — APPROVED** [review]
Thank you!
