### PR TITLE
Remove extras from old params in named routes

### LINKED ISSUE #906: Using named route persists old route params
### Vue.js version
2.0.5

### Vue-Router version
2.0.2

### Reproduction Link

https://jsfiddle.net/erikgall/spz2j6o6/

### Steps to reproduce / What is happening

The problem occurs when navigating back to a parent route (or sibling route) with no parameters from a child route that has a parameter. The bug seems to only happen when using named routes as well.

```
// current path: /students/classrooms/1
<router-link :to="{ name: 'students.classrooms'  }">All Classrooms</router-link>
```

#### Component/Route Hierarchy

root component --> layout component (ex. student, instructor, guest) --> page component

-> ./app.vue
---> ./students.vue
------->./students/index.vue
-------> ./students/classrooms/index.vue (path: `students/classrooms`)
-------> ./students/classrooms/show.vue (path: `students/classrooms/:classroom`)

When navigating from the show.vue component to any other component the classroom param persists and is not removed.

`students/classrooms/:classroom` to `students/classrooms`

This is an issue if you depend on using a v-if directive to render a component that should be inserted if a route param exists like in the example below.

### What is Expected?

If a route contains a param it should be present in the `vm.$route.params` object and when navigating from that route to a new one the params object is updated to reflect the current url.

### PR DESCRIPTION
**Pull request by znck**
Fixes #906

### CODE REVIEW

**Comment by fnlctrl** [comment]
Thanks for the PR! I'll review it asap.

File: src/create-matcher.js [hunk 1]
```diff
@@ -198,6 +203,26 @@ function fillParams (
...
+  const hit = regexpParamsCache[path]
+
+  if (hit) {
+    return hit
+  }
+
+  const keys = []
+  const paramNames: Array<string> = []
+
+  Regexp(path, keys)
```
Comment (fnlctrl) [inline src/create-matcher.js]: We don't have to call `Regexp(path)` here again (without cache, actually), there's already code for getting cached keys and regexp here (https://github.com/znck/vue-router/blob/ab0a779ba6f09f5b28138c9445ce84d7263daef6/src/create-matcher.js#L163-L172). 

We should probably create a separate function that uses the code above, take a `path` as only parameter, returns a `{keys, regexp}` object, maybe name it `getKeysAndParams`.

Then we can get keys with ES6 destructuring

``` js
const {keys} = getKeysAndParams(path)
```

File: src/create-matcher.js [hunk 2]
```diff
@@ -198,6 +203,26 @@ function fillParams (
...
+
+  for (let i = 0, len = keys.length; i < len; ++i) {
+    const key = keys[i]
+    if (key && 'name' in key) paramNames.push(key.name)
+  }
```
Comment (fnlctrl) [inline src/create-matcher.js]: This whole for-loop can be simplified to `keys.map(k => k.name)` for brevity. Since we are already using cache here, the performance penalty of using a `Array.prototype.map` is negligible.

File: src/create-matcher.js [hunk 3]
```diff
@@ -31,14 +35,15 @@ export function createMatcher (routes: Array<RouteConfig>): Matcher {
 
     if (name) {
       const record = nameMap[name]
+      const paramNames = getParams(record.path)
```
Comment (fnlctrl) [inline src/create-matcher.js]: We can use [similar code here](https://github.com/znck/vue-router/blob/ab0a779ba6f09f5b28138c9445ce84d7263daef6/src/create-matcher.js#L196-L198) to avoid a separate  getParams function

**Review by fnlctrl — CHANGES_REQUESTED** [review]
@znck  Also, can we add accompanying e2e tests for it (that addresses https://github.com/vuejs/vue-router/issues/906)?
The test provided in the original PR (https://github.com/vuejs/vue-router/pull/851/files) didn't actually cover the case of `using extra params`, we should probably fix it too so that this PR can cover both cases (bugfix and using extra params)

File: src/create-matcher.js [hunk 4]
```diff
@@ -198,6 +203,26 @@ function fillParams (
...
+  const paramNames: Array<string> = []
+
+  Regexp(path, keys)
+
+  for (let i = 0, len = keys.length; i < len; ++i) {
+    const key = keys[i]
+    if (key && 'name' in key) paramNames.push(key.name)
+  }
+
+  return (regexpParamsCache[path] = paramNames)
```
Comment (fnlctrl) [inline src/create-matcher.js]: This can then be simplified to 

``` js
return regexpParamsCache[path] || 
   (regexpParamsCache[path] = keys.map(k => k.name))
```

like https://github.com/znck/vue-router/blob/ab0a779ba6f09f5b28138c9445ce84d7263daef6/src/create-matcher.js#L196-L198

**Review by fnlctrl — APPROVED** [review]
/ping @yyx990803

**Comment by jeerbl** [comment]
+1

**Comment by yyx990803** [comment]
👍 great work @znck and @fnlctrl
