### PR TITLE
Prevent unnecessary Exception with non-existent links 

### LINKED ISSUE #1386: Missing named routes throw TypeErrors
### Version
2.5.2

### Reproduction link
[http://jsfiddle.net/qkco53b9/1/](http://jsfiddle.net/qkco53b9/1/)

### Steps to reproduce
Run the example. Look at the console.

### What is expected?
Inserting a router link to a named route that doesn't exist should warn.

### What is actually happening?
The console spews both warnings about the missing named routes and errors about not being able to access the `regex` property of a route.

---
I'm building an SPA and inserting placeholder links to pages I haven't built yet.

It looks like the problem might be here: https://github.com/vuejs/vue-router/blob/4de549a45cc38975d6ce343ecdea007972891b4f/src/create-matcher.js#L39. Seems the matcher still tries to proceed even if there's no record.

### PR DESCRIPTION
**Pull request by posva**
Closes #1386

### CODE REVIEW

**Review by kazupon — APPROVED** [review]

File: src/create-matcher.js [hunk 1]
```diff
@@ -33,8 +33,9 @@ export function createMatcher (
 
     if (name) {
       const record = nameMap[name]
-      if (process.env.NODE_ENV !== 'production') {
-        warn(record, `Route with name '${name}' does not exist`)
+      if (process.env.NODE_ENV !== 'production' && !record) {
```
Comment (yyx990803) [inline src/create-matcher.js]: behavior should be consistent between prod and dev, so we should move the env check to only apply to the warning.

**Review by yyx990803 — CHANGES_REQUESTED** [review]

**Comment by posva** [comment]
I forgot to ping you @yyx990803 😓
